namespace AElf.Contract.SourceGenerator.Generator;

public class ContractStateGenerator
{
    public (string, string) Generate(string stateTypeName)
    {
        var className = stateTypeName.Split('.').Last();
        var ns = stateTypeName.Replace($".{className}", "");
        return ($"{className}.g.cs", @$"// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
// </auto-generated>
using AElf.Sdk.CSharp.State;

namespace {ns};

public partial class {className} : ContractState
{{
}}
");
    }
}