using ContractGenerator.Primitives;
using Google.Protobuf.Reflection;

namespace ContractGenerator;

public class ServiceGenerator : AbstractGenerator
{
    private FileDescriptor _fileDescriptor;

    public ServiceGenerator(FileDescriptor fileDescriptor, GeneratorOptions options) : base(options)
    {
        _fileDescriptor = fileDescriptor;
    }

    public override string? Generate()
    {
        switch (_fileDescriptor.Services.Count)
        {
            // Don't write out any output if there no services, to avoid empty service
            // files being generated for proto files that don't declare any.
            case 0:
                return "";
            case > 1:
                throw new Exception(_fileDescriptor.Name + ": File contains more than one service.");
        }

        // Don't write out any output if there no event for event-only generation
        // scenario, this is usually for base contracts
        if (Options.GenerateEventOnly && !_fileDescriptor.ContainsEvent()) return "";

        // Write out a file header.
        PrintLine(
            @"
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: {_fileDescriptor.Name}
// </auto-generated>
             ");

        // use C++ style as there are no file-level XML comments in .NET
        // string leadingComments = GetCsharpComments(file, true);  TODO uncomment once PR merged
        // if (!leadingComments.empty()) {
        //     Print("// Original file comments:\n");
        //         PrintRaw(leading_comments.c_str());
        // }

        PrintLine("#pragma warning disable 0414, 1591");
        ___EmptyLine___();

        InRegion("Designer generated code", () =>
        {
            ___EmptyLine___();
            PrintLine(
                @"
using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;
                ");
            ___EmptyLine___();
            Print($"namespace {_fileDescriptor.GetNamespace()} ");
            InBlock(() =>
            {
                Events();
                ContractContainer();
            });
        });

        return PrintOut();
    }

    private void Events()
    {
        if (!Options.GenerateEvent) return;
        // Events are not needed for contract reference
        ___EmptyLine___();
        InRegion("Events", () =>
        {
            foreach (var msg in _fileDescriptor.MessageTypes)
            {
                PrintIgnoreWhitespace(new EventTypeGenerator(msg, Options).Generate());
            }
        });
        ___EmptyLine___();
    }

    private void ContractContainer()
    {
        if (!Options.GenerateContainer) return;
        foreach (var svc in _fileDescriptor.Services)
        {
            PrintIgnoreWhitespace(new Generator(svc, Options).Generate());
        }
    }
}
